---
- name: Create the rpi_exporter group
  group:
    name: "{{ rpi_exporter_system_group }}"
    state: present
    system: true
  when: rpi_exporter_system_group != "root"

- name: Create the rpi_exporter user
  user:
    name: "{{ rpi_exporter_system_user }}"
    group: "{{ rpi_exporter_system_group }}"
    groups:
      - video
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: rpi_exporter_system_user != "root"

- name: Download rpi_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/lukasmalkmus/rpi_exporter/releases/download/v{{ rpi_exporter_version }}/rpi_exporter-{{ rpi_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/rpi_exporter-{{ rpi_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ rpi_exporter_checksum }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Unpack rpi_exporter binary
  become: false
  unarchive:
    src: "/tmp/rpi_exporter-{{ rpi_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/rpi_exporter-{{ rpi_exporter_version }}.linux-{{ go_arch }}/rpi_exporter"
  delegate_to: localhost
  check_mode: false

- name: Propagate rpi_exporter binaries
  copy:
    src: "/tmp/rpi_exporter-{{ rpi_exporter_version }}.linux-{{ go_arch }}/rpi_exporter"
    dest: "/usr/local/bin/rpi_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart rpi_exporter
  when: not ansible_check_mode
